# Generated by Django 3.1.1 on 2020-11-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='album',
            new_name='category',
        ),
    ]
