# Generated by Django 3.1.1 on 2020-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_TBL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('number', models.CharField(max_length=50, verbose_name='NUMBER')),
                ('email', models.CharField(max_length=50, verbose_name='EMAIL')),
                ('status', models.CharField(max_length=50, verbose_name='STATUS')),
                ('major', models.CharField(max_length=50, verbose_name='MAJOR')),
                ('address', models.CharField(max_length=50, verbose_name='ADDRESS')),
            ],
            options={
                'ordering': ('number', 'name'),
            },
        ),
    ]
