# Generated by Django 3.1.1 on 2020-10-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('id', 'name')},
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='TITLE')),
                ('number', models.CharField(max_length=50, verbose_name='NUMBER')),
                ('major', models.CharField(max_length=50, verbose_name='MAJOR')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugang.subject')),
            ],
            options={
                'ordering': ('name', 'number', 'major'),
            },
        ),
    ]
