# Generated by Django 3.1.1 on 2020-11-04 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sugang', '0003_auto_20201028_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GRADE'),
        ),
        migrations.AddField(
            model_name='student',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER'),
        ),
        migrations.AddField(
            model_name='subject',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER'),
        ),
        migrations.AddField(
            model_name='subject',
            name='place',
            field=models.CharField(default=2, max_length=30, verbose_name='PLACE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='professor',
            field=models.CharField(default=2, max_length=30, verbose_name='PROFESSOR'),
            preserve_default=False,
        ),
    ]
